### ISSUE TITLE
Q-A type communication

### ISSUE THREAD

**Issue by fuatsengul** [voodootikigod/node-serialport#556]
Hi there, 
I have a device to communicate that receives certain commands and responses with corresponding data.

I have crawled around to find a useful way but I couldn't.
With on('data') hook all responses goes into same place and It became uncontrollable when mass data is need to be send.
Any help will be appreciated :)
Thanks.

**Comment by jacobrosenthal** [comment]
I dont know what you mean by Q/A type, maybe question answer, but heres my answer. You should either use or create whats called a [parser](https://github.com/voodootikigod/node-serialport#parsers)  so that youre on data only get called everytime you get your delimeter (like space or newline), or you should buffer your data at the on.data and have some logic in here to call a funciton when you've receive an appropriate amount of data to answer
